version: '1'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  mysql_master:
    image: mysql:latest
    container_name: mysql_master
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3306:3306"

  mysql_slave:
    image: mysql:latest
    container_name: mysql_slave
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: "mysql_master,mysql_slave"
      PMA_ARBITRARY: 1 
    depends_on:
      - mysql_master
      - mysql_slave
    ports:
      - "8081:80"

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    ports:
      - "8082:80"
    environment:
      - WORDPRESS_DB_HOST=mysql_master
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=replica
      - WORDPRESS_TABLE_PREFIX=wp1_

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    ports:
      - "8083:80"
    environment:
      - WORDPRESS_DB_HOST=mysql_master
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=replica
      - WORDPRESS_TABLE_PREFIX=wp2_
   
  wordpress3:
    image: wordpress:latest
    container_name: wordpress3
    ports:
      - "8084:80"
    environment:
      - WORDPRESS_DB_HOST=mysql_master
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=replica
      - WORDPRESS_TABLE_PREFIX=wp3_
    